name: Deploy SKY-TO-BE-MEDIA to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 1. Préparer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 2. Installer et Construire
        run: |
          npm install
          npm run build

      - name: 3. Préparer le dossier sur le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/skytobemedia.com
            sudo chown -R ubuntu:ubuntu /var/www/skytobemedia.com
            sudo rm -rf /var/www/skytobemedia.com/*

      - name: 4. Envoyer les fichiers (Dossier 'dist' forcé)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist" 
          target: "/var/www/skytobemedia.com/"
          strip_components: 1

      - name: 5. Sécuriser les droits pour Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/skytobemedia.com/
